Fix grep -A -B bug, Add dual params support

diff --git a/smysql b/smysql
--- a/smysql
+++ b/smysql
@@ -5,16 +5,16 @@ if [ x"${comm}" = x"smysql-passwd" ]
 then
 
 echo 'enter mysql passwd:'
-mysql_passwd=`read`
+read mysql_passwd
 echo 'enter [your passwd]:'
-echo ${mysql_passwd}|openssl enc -aes256 -e -a
+echo ${mysql_passwd}|openssl enc -aes256 -e -a|xargs| tr -d ' '
 
 else
 
 config_file=~/.smysql/config
 host_arg=${1}
 
-source <(grep -iA7 "^ *host  *${host_arg} *$" ${config_file} |sed 's/^ *\([^ ]\{1,\}\) *\([^ ]\{1,\}\) *$/\1=\2/')
+source <(grep -m1 -iA20 "^ *host  *${host_arg} *$" ${config_file} |grep -m1 -B20 "^ *$"|sed 's/^ *\([^ ]\{1,\}\) *\([^ ]\{1,\}\) *$/\1=\2/')
 
 if [ x"${host}" = x"" ]
 then
@@ -44,21 +44,49 @@ then
     param_database=-D${database}
 fi
 
-
 if [ x"${passwd}" = x"" ]
 then
-    echo "[ ${host} ] "${comm:1} -u${user} -P${port} -p -h${hostname} ${param_database} ${2} ${3} ${4} ${5} ${6} ${7} ${8} ${9}
-    echo "enter mysql passwd"
+    echo "[ ${host} ] "${comm:1} -u${user} -P${port} -p -h${hostname} ${param_database} >&2
+    echo "enter mysql passwd" >&2
 else
-    echo "[ ${host} ] "${comm:1} -u${user} -P${port} -p AES256-decode\([your passwd]\) -h${hostname} ${param_database} ${2} ${3} ${4} ${5} ${6} ${7} ${8} ${9}
-    echo "enter [your passwd]:"
-    passwd=`echo ${passwd}|openssl enc -aes256 -d -a`
-    if [ 0 != $? ]
+    if [ x`echo ${passwd}|grep -o "^U2FsdGVkX1"` == x'U2FsdGVkX1' ]
     then
-        echo "[your passwd] error"
-        exit
+        echo "[ ${host} ] "${comm:1} -u${user} -P${port} -p AES256-decode\([your passwd]\) -h${hostname} ${param_database} >&2
+        echo "enter [your passwd]:" >&2
+        passwd=`echo ${passwd}|openssl enc -aes256 -d -a`
+        if [ 0 != $? ]
+        then
+            echo "[your passwd] error" >&2
+            exit
+        fi
+    else
+        echo "[ ${host} ] "${comm:1} -u${user} -P${port} -p${passwd} -h${hostname} ${param_database} >&2
+        passwd=$passwd
     fi
 fi
-${comm:1} -u${user} -P${port} -p${passwd} -h${hostname} ${param_database} ${2} ${3} ${4} ${5} ${6} ${7} ${8} ${9}
+
+case $# in
+    1)
+        ${comm:1} -u${user} -P${port} -p${passwd} -h${hostname} ${param_database}
+        ;;
+    2)
+        ${comm:1} -u${user} -P${port} -p${passwd} -h${hostname} ${param_database} "${2}"
+        ;;
+    3)
+        ${comm:1} -u${user} -P${port} -p${passwd} -h${hostname} ${param_database} "${2}" "${3}"
+        ;;
+    4)
+        ${comm:1} -u${user} -P${port} -p${passwd} -h${hostname} ${param_database} "${2}" "${3}" "${4}"
+        ;;
+    5)
+        ${comm:1} -u${user} -P${port} -p${passwd} -h${hostname} ${param_database} "${2}" "${3}" "${4}" "${5}"
+        ;;
+    6)
+        ${comm:1} -u${user} -P${port} -p${passwd} -h${hostname} ${param_database} "${2}" "${3}" "${4}" "${5}" "${6}"
+        ;;
+    *)
+        echo "bad num of args: ${#}"
+        ;;
+esac
 
 fi
